name: Start a run from Python file on local server via self-hosted Github Actions runner

on:
  push:
    branches:
      - development
    paths:
      - 'src/**'
    
jobs:
  run-files-in-development-environment:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip --break-system-packages
        python3 -m pip install pandas numpy "kfp>=2.0.0" scikit-learn --break-system-packages
        
    - name: Connect to local server and run the Python files
      run: |       
        python3 src/submit_run.py