name: Start a run from Jupyter Notebook on local server via self-hosted Github Actions runner
 
on:

  push:

    branches:

      - development

    paths:

      - 'notebooks/**'
 
jobs:

  run-notebook-in-development-environment:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies

      run: |

        python3 -m pip install --upgrade pip --break-system-packages

        python3 -m pip install "kfp>=2.0.0" --break-system-packages

    - name: Connect to local server and run the Notebook      

      run: |       

        jupyter nbconvert --execute --to notebook --inplace notebooks/demo-pipeline.ipynb
 